### ISSUE TITLE
Print bibliography with this theme requires \printbibliography[heading=none]

### ISSUE THREAD

**Issue by solarchemist** [luistar/unina-beamer#1]
When using `biblatex` with this theme the bibliography does not result in a list of references as expected, but instead creates a "standout" page. This is at first puzzling, until you realize that this theme is *capturing* `AtBeginSection` if the `sectionpages` option is set ([see source](https://github.com/luistar/unina-beamer/blob/b2464035d32faa926ea9cc5e43da21d2a4cdc6e7/beamerinnerthemeUniNA.sty#L141C19-L141C19)) , and `\printbibliography` creates a section header by default.

To anyone else trying to get `biblatex` to work, just omit the heading when printing the bibliography: `\printbibliography[heading=none]`. The bibliography is now printed as expected!

```
\documentclass[10pt,aspectratio=43]{beamer}
\usetheme[sectionpages]{UniNA}

\begin{filecontents}{\jobname.bib}
@article{A2012,
author = {Author, A},
title = {An interesting paper},
journal = {Journal},
year = {2012},
volume = {2},
pages = {70--76},
}
@article{B2012,
author = {Buthor, B},
title = {An also interesting paper},
journal = {Journal},
year = {2012},
volume = {2},
pages = {77--79},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

\begin{frame}{Outline}
   \tableofcontents
\end{frame}

\begin{frame}
   \textcite{A2012}
\end{frame}

\appendix

\begin{frame}[t,allowframebreaks]
   \frametitle{Bibliography}
   \printbibliography[heading=none]
\end{frame}

\end{document}
```

+ https://tex.stackexchange.com/questions/102692/omit-heading-in-biblatex-with-printbibliography

**Comment by luistar** [comment]
Thank you for highlighting this issue! I updated the example in the repository to showcase how to include bibliography slides as well.
